#!/usr/bin/env python3
"""Tests for the pre-commit hook guard in install/setup_deps.py (VAL-712).

`make setup` / `install/setup.ps1 -Setup` call `setup_deps.py --hook`. `pre-commit
install` writes the interpreter that ran it into the clone's shared
.git/hooks/pre-commit, so the guard only runs it when no hook exists, when the
existing hook's INSTALL_PYTHON path is gone, or when --force-hook is given.

Each test builds a throwaway git repo and fake hook files; the pre-commit runner is
injected, so the real pre-commit (and the real .git/hooks/pre-commit) is never touched.

Stdlib only. Run as: py -3.13 install/test_setup_deps.py
"""

from __future__ import annotations

import contextlib
import io
import shlex
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent))
import setup_deps

HOOK_TEMPLATE = """#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON={python}
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated
"""


class FakeRunner:
    """Records commands; `available` controls the `pre_commit --version` probe."""

    def __init__(self, available: bool = True) -> None:
        self.available = available
        self.calls: list[list[str]] = []

    def __call__(self, cmd: list[str], cwd: Path, quiet: bool) -> int:
        self.calls.append(cmd)
        if cmd[-1] == "--version":
            return 0 if self.available else 1
        return 0

    @property
    def installs(self) -> list[list[str]]:
        return [c for c in self.calls if c[-2:] == ["pre_commit", "install"]]


class HookGuardTest(unittest.TestCase):
    def setUp(self) -> None:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.repo = Path(tmp.name) / "repo"
        self.repo.mkdir()
        subprocess.run(["git", "init", "-q", str(self.repo)], check=True)
        (self.repo / ".pre-commit-config.yaml").write_text(
            "repos: []\n", encoding="utf-8"
        )
        self.hook = self.repo / ".git" / "hooks" / "pre-commit"
        self.python = ["/fake/python"]
        # An interpreter path that exists: any real file stands in for one.
        self.live_python = Path(tmp.name) / "python.exe"
        self.live_python.write_text("", encoding="utf-8")

    def write_hook(self, python: str | None) -> None:
        self.hook.parent.mkdir(parents=True, exist_ok=True)
        if python is None:
            body = "#!/bin/sh\necho custom hook\n"
        else:
            body = HOOK_TEMPLATE.format(python=shlex.quote(python))
        self.hook.write_text(body, encoding="utf-8")

    def guard(
        self, force: bool = False, runner: FakeRunner | None = None
    ) -> tuple[int, str, FakeRunner]:
        run = runner or FakeRunner()
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            rc = setup_deps.install_hook(
                self.repo, force=force, python=self.python, run=run
            )
        return rc, out.getvalue(), run

    def test_hook_path_resolves_through_git(self) -> None:
        self.assertEqual(setup_deps.hook_file(self.repo).resolve(), self.hook.resolve())

    def test_install_python_parsed_from_pre_commit_hook(self) -> None:
        self.write_hook(r"C:\Program Files\Python313\python.exe")
        self.assertEqual(
            setup_deps.install_python(self.hook),
            r"C:\Program Files\Python313\python.exe",
        )

    def test_no_hook_installs(self) -> None:
        rc, _, run = self.guard()
        self.assertEqual(rc, 0)
        self.assertEqual(run.installs, [[*self.python, "-m", "pre_commit", "install"]])

    def test_existing_hook_with_live_interpreter_is_kept(self) -> None:
        self.write_hook(str(self.live_python))
        before = self.hook.read_text(encoding="utf-8")
        rc, out, run = self.guard()
        self.assertEqual(rc, 0)
        self.assertEqual(run.installs, [])
        self.assertEqual(self.hook.read_text(encoding="utf-8"), before)
        note = [line for line in out.splitlines() if line.strip()]
        self.assertEqual(len(note), 1, out)
        self.assertIn("--force-hook", note[0])
        self.assertIn(str(self.live_python), note[0])

    def test_existing_hook_with_missing_interpreter_reinstalls(self) -> None:
        self.write_hook(str(self.live_python.parent / "gone" / "python.exe"))
        rc, _, run = self.guard()
        self.assertEqual(rc, 0)
        self.assertEqual(len(run.installs), 1)

    def test_force_hook_reinstalls_over_live_interpreter(self) -> None:
        self.write_hook(str(self.live_python))
        rc, _, run = self.guard(force=True)
        self.assertEqual(rc, 0)
        self.assertEqual(len(run.installs), 1)

    def test_foreign_hook_without_install_python_is_kept(self) -> None:
        self.write_hook(None)
        rc, out, run = self.guard()
        self.assertEqual(rc, 0)
        self.assertEqual(run.installs, [])
        self.assertIn("--force-hook", out)

    def test_no_config_skips(self) -> None:
        (self.repo / ".pre-commit-config.yaml").unlink()
        rc, out, run = self.guard(force=True)
        self.assertEqual(rc, 0)
        self.assertEqual(run.calls, [])
        self.assertIn("skip: no .pre-commit-config.yaml", out)

    def test_pre_commit_missing_skips(self) -> None:
        rc, out, run = self.guard(runner=FakeRunner(available=False))
        self.assertEqual(rc, 0)
        self.assertEqual(run.installs, [])
        self.assertIn("skip: pre-commit not installed", out)

    def test_install_failure_propagates(self) -> None:
        class Failing(FakeRunner):
            def __call__(self, cmd: list[str], cwd: Path, quiet: bool) -> int:
                super().__call__(cmd, cwd, quiet)
                return 0 if cmd[-1] == "--version" else 3

        rc, _, _ = self.guard(runner=Failing())
        self.assertEqual(rc, 3)


class MainRoutingTest(unittest.TestCase):
    def test_hook_flag_runs_only_the_guard(self) -> None:
        with (
            mock.patch.object(setup_deps, "install_hook", return_value=0) as guard,
            mock.patch.object(setup_deps.subprocess, "call") as call,
        ):
            self.assertEqual(setup_deps.main(["--hook"]), 0)
        guard.assert_called_once()
        self.assertFalse(guard.call_args.kwargs["force"])
        call.assert_not_called()

    def test_force_hook_flag_implies_hook_and_force(self) -> None:
        with mock.patch.object(setup_deps, "install_hook", return_value=0) as guard:
            self.assertEqual(setup_deps.main(["--force-hook"]), 0)
        self.assertTrue(guard.call_args.kwargs["force"])

    def test_default_does_not_touch_hook(self) -> None:
        out = io.StringIO()
        with (
            mock.patch.object(setup_deps, "install_hook") as guard,
            contextlib.redirect_stdout(out),
        ):
            setup_deps.main(["--dry-run"])
        guard.assert_not_called()


if __name__ == "__main__":
    unittest.main()
